### ISSUE TITLE
[Bug]: No ability to propose a feature on GitHub

### ISSUE THREAD

**Issue by CWSpear** [oceanroleplay/discord.ts#210]
### What happened?

The contributing guidelines mention "Proposing new features," but there are only templates for reporting a but or a security vulnerability.

**Expected:** I can go to Issues and propose a feature via a feature template.

**Actual:** If I want to propose a feature, I have to use a bug/security template.

### Reproduction

Go to Issues. See that there isn't a feature (or blank) template.

### Version

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oceanroleplay** [comment]
I would prefer to use GitHub discussion with category idea, since that would be right place for a discussion.

**Comment by CWSpear** [comment]
I'm not familiar with Discussions. I don't know anyone else that uses it. And I didn't see anything in Contributing. I'll try and check over there, tho. Thanks.

**Comment by oceanroleplay** [comment]
now added a issue template as well. https://github.com/oceanroleplay/discord.ts/issues/new/choose

**Comment by CWSpear** [comment]
Nice. Thanks!
