### ISSUE TITLE
[Feature]: Interaction event matching

### ISSUE THREAD

**Issue by CWSpear** [oceanroleplay/discord.ts#211]
### What happened?

I have a scenario where you can do a search to display an image of one of 100s of cards. Sometimes there are multiple matches (there are even similar versions of the card with the exact same name), and so I dynamically display buttons so that you can choose the best match.

The problem I'm facing, is I don't have a way to know which card was selected in this scenario. My old version would set the buttons custom ID to the unique ID for the card, and use that to display the correct one when they created that. But I can't viably register `@ButtonComponent` for every single card to handle updating the card.

If possible, it'd be nice to have something like glob matching for button IDs. For example:

```ts
  @ButtonComponent('card-btn_*')
  async pickCard(interaction: ButtonInteraction) {
    const [, cardId] = interaction.customId.split('_');
    
    await interaction.editReply(getCardMessageById(cardId));
  }
```

### Reproduction

Feature request, N/A

### Version

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oceanroleplay** [comment]
you should prefer `@On` wrapper for this task. since customid is not fixed.

**Comment by oceanroleplay** [comment]
however, will see if it's possible to add regex support 😉

**Comment by oceanroleplay** [comment]
Added regex support for button/selectmenu decorators, this would resolve many common case for developers.

**Comment by Satont** [comment]
> Added regex support for button/selectmenu decorators, this would resolve many common case for developers.

Thats what i'm also asked for once in discord, thank you!
