### ISSUE TITLE
[Bug]: Partialy update permissions on interactions.

### ISSUE THREAD

**Issue by Satont** [oceanroleplay/discord.ts#237]
### Feature?

I noticed i got error on command permissiions update. I'm interested does it on requests or limit at all.
```
2021-11-13T17:46:05.814699828Z DiscordAPIError: Invalid Form Body
--
2 | 2021-11-13T17:46:05.814726709Z permissions: Must be 10 or fewer in length.
3 | 2021-11-13T17:46:05.814729949Z at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
4 | 2021-11-13T17:46:05.814732669Z at processTicksAndRejections (node:internal/process/task_queues:96:5)
5 | 2021-11-13T17:46:05.814735109Z at RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
6 | 2021-11-13T17:46:05.814737749Z at ApplicationCommandPermissionsManager.set (/app/node_modules/discord.js/src/managers/ApplicationCommandPermissionsManager.js:168:20)
7 | 2021-11-13T17:46:05.814740389Z at /app/node_modules/discordx/src/Client.ts:690:15
8 | 2021-11-13T17:46:05.814742709Z at async Promise.all (index 1)
9 | 2021-11-13T17:46:05.814744829Z at MyClient.initGuildApplicationPermissions (/app/node_modules/discordx/src/Client.ts:659:5)
10 | 2021-11-13T17:46:05.814747629Z at async Promise.all (index 0)
11 | 2021-11-13T17:46:05.814749789Z at MyClient.initApplicationPermissions (/app/node_modules/discordx/src/Client.ts:623:5)
12 | 2021-11-13T17:46:05.814752149Z at Ready.ready (/app/src/bot/events/ready.ts:25:5) {
13 | 2021-11-13T17:46:05.814754389Z method: 'put',
14 | 2021-11-13T17:46:05.814756469Z path: '/applications/909109398096461894/guilds/768750988395806730/commands/909135362935369749/permissions',
15 | 2021-11-13T17:46:05.814758909Z code: 50035,
16 | 2021-11-13T17:46:05.814760989Z httpStatus: 400,
17 | 2021-11-13T17:46:05.814763069Z requestData: { json: { permissions: [Array] }, files: [] }
18 | 2021-11-13T17:46:05.814765309Z }
```

If it's limited per requests might be good to partiallly send requests.

### Package

discordx

**Comment by oceanroleplay** [comment]
I can't reproduce this issue.

**Comment by oceanroleplay** [comment]
I tried like sending 14 permissions body to a command

**Comment by Satont** [comment]
```ts
import { Guild, PermissionResolvable, ApplicationCommandPermissions, Role, Permissions } from 'discord.js';

export const commandPermission = async (guild: Guild, permission: PermissionResolvable | PermissionResolvable[], oneOf: boolean = true) => {
  const perms = Array.isArray(permission) ? permission : [permission];
  const hasPerm = (p: Permissions) => {
    if (oneOf) {
      return perms.some((perm) => p.has(perm));
    } else return perms.every((perm) => p.has(perm));
  };

  const [roles] = await Promise.all([guild.roles.fetch(), guild.members.fetch()]);
  return [...roles.values()]
    .filter((instance) => hasPerm(instance.permissions))
    .map((instance): ApplicationCommandPermissions => {
      return { id: instance.id, permission: true, type: instance instanceof Role ? 'ROLE' : 'USER' };
    });
};
```

```ts
@Permission((guild) => commandPermission(guild, 'MANAGE_MESSAGES'))
```

Thats how i getting this.

**Comment by oceanroleplay** [comment]
> ```ts
> import { Guild, PermissionResolvable, ApplicationCommandPermissions, Role, Permissions } from 'discord.js';
> 
> export const commandPermission = async (guild: Guild, permission: PermissionResolvable | PermissionResolvable[], oneOf: boolean = true) => {
>   const perms = Array.isArray(permission) ? permission : [permission];
>   const hasPerm = (p: Permissions) => {
>     if (oneOf) {
>       return perms.some((perm) => p.has(perm));
>     } else return perms.every((perm) => p.has(perm));
>   };
> 
>   const [roles] = await Promise.all([guild.roles.fetch(), guild.members.fetch()]);
>   return [...roles.values()]
>     .filter((instance) => hasPerm(instance.permissions))
>     .map((instance): ApplicationCommandPermissions => {
>       return { id: instance.id, permission: true, type: instance instanceof Role ? 'ROLE' : 'USER' };
>     });
> };
> ```
> 
> ```ts
> @Permission((guild) => commandPermission(guild, 'MANAGE_MESSAGES'))
> ```
> 
> Thats how i getting this.

only the final json output matter, I tried sending more than 10 permisisons in single request as error says, send 10 or fewer, can't reproduce it.

**Comment by oceanroleplay** [comment]
Perhaps, you can raise this issue with djs instead, since this is not related to discordx?

**Comment by Satont** [comment]
> Perhaps, you can raise this issue with djs instead, since this is not related to discordx?

True. Anyway thank you.

**Comment by oceanroleplay** [comment]
you can have upto 10 permissions per command. Hence you can not add more than 10.

[ref: discord doc](https://discord.com/developers/docs/interactions/application-commands#batch-edit-application-command-permissions)
