### ISSUE TITLE
[Bug]: TypeError when playing a Youtube song with @discordx/music

### ISSUE THREAD

**Issue by tonyd33** [oceanroleplay/discord.ts#306]
### What happened?

When playing a song with `Queue.play`, nothing is played. Looking at the stacktrace, it seems like `Queue.processQueue` throws an error that's caught and it tries to emit an error, and tries to index `error.resource.metadata`, but that causes an error (See below). The problem seems to be twofold: the song isn't being played, and the error handling causes an error.

node version: 16.6.0
OS: Arch Linux (5.14.14-arch1-1)

If there is any other relevant information I should include, let me know.

### Reproduction

[Link to repo](https://github.com/tonyd33/BananaBotJS)

To reproduce, paste in the bot token to `bot_token`, get the bot running and run `~test` in a server while connected to a voice channel. Key file to look at are [youtubePlayer.ts](https://github.com/tonyd33/BananaBotJS/blob/master/src/commands/youtubePlayer.ts)

### Package

@discordx/music

### Version

Stable

### Relevant log output

```shell
➜  BananaBotJS yarn run start
yarn run v1.22.17
$ nodemon --exec BOT_TOKEN=`cat bot_token` node --loader ts-node/esm/transpile-only src/index.ts
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `BOT_TOKEN=<omitted> node --loader ts-node/esm/transpile-only src/index.ts`
(node:2134137) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
BananaTesting >> global >> command >> adding 0 []
BananaTesting >> global >> command >> deleting 0 []
BananaTesting >> global >> command >> updating 0 []
Bot started
TypeError: Cannot read property 'metadata' of undefined
    at MyQueue.processQueue (file:///home/tony/repos/BananaBotJS/node_modules/@discordx/music/src/YoutubePlayer/core/Queue.ts:272:56)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[nodemon] app crashed - waiting for file changes before starting...
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oceanroleplay** [comment]
before testing the repo, yous need to move the Player object outside slash command. check music example for more details.

**Comment by oceanroleplay** [comment]
please use [discord-music-bot](https://github.com/oceanroleplay/discord-music-bot) example and join our [discord server](https://discord.gg/yHQY9fexH9) for close discussion and support.

**Comment by tonyd33** [comment]
Thanks. I should have reached out on the discord server first; didn’t realize there was one. It might be helpful to reference the example in the music package’s README.

**Comment by oceanroleplay** [comment]
> Thanks. I should have reached out on the discord server first; didn’t realize there was one. It might be helpful to reference the example in the music package’s README.

Alright, will add discord server link on all our package's readme.

**Comment by tonyd33** [comment]
> > Thanks. I should have reached out on the discord server first; didn’t realize there was one. It might be helpful to reference the example in the music package’s README.
> 
> Alright, will add discord server link on all our package's readme.

Ah sorry, my reply was confusing. I had meant adding the [music bot example](https://github.com/oceanroleplay/discord-music-bot) to the README, but that’s a good idea too

**Comment by oceanroleplay** [comment]
> > > Thanks. I should have reached out on the discord server first; didn’t realize there was one. It might be helpful to reference the example in the music package’s README.
> > 
> > 
> > Alright, will add discord server link on all our package's readme.
> 
> Ah sorry, my reply was confusing. I had meant adding the [music bot example](https://github.com/oceanroleplay/discord-music-bot) to the README, but that’s a good idea too

still confusing, the bot example link is on readme but of discordx package, did you mean for @discordx/music?

**Comment by tonyd33** [comment]
> > > > Thanks. I should have reached out on the discord server first; didn’t realize there was one. It might be helpful to reference the example in the music package’s README.
> > > 
> > > 
> > > Alright, will add discord server link on all our package's readme.
> > 
> > 
> > Ah sorry, my reply was confusing. I had meant adding the [music bot example](https://github.com/oceanroleplay/discord-music-bot) to the README, but that’s a good idea too
> 
> still confusing, the bot example link is on readme but of discordx package, did you mean for @discordx/music?

Yeah. As far as I can tell, I didn't see any mention of it for @discordx/music but I see you just added it. Thanks.
