### ISSUE TITLE
[Bug]: rate limited on initApplicationCommands

### ISSUE THREAD

**Issue by Pho3niX90** [oceanroleplay/discord.ts#392]
### What happened?

Switching over from discordts to discordx, I added slashes for the first time. 

Upon deployment, I noticed I was rate limited before the operation completed (even in test environment).  

### Reproduction

My scenario. 

Add new slashes
Run bot (guilds 500+)
Get rate limited. 
--------------------------------------------------------
My calcs are as follows, before rate limited 
167 missing perm discords (for slashes), therefore, my assumption is they did not issue all commands (update, create, delete)
38 with perms

Then rate limited, so non of the remainder of the  servers are update, nor is the bot receiving or sending any commands (due to being rate limited). In this scenario, everytime the bot restarts, it would take multiple hours of downtime. 

### Package

discordx

### Version

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oceanroleplay** [comment]
such problems are related to discordjs and your usage apart from that, if you are using guild commands then it's not a good practice, you should use global commands, couldn't say much without more information, you can join our discord server and ask for support there.

**Comment by Pho3niX90** [comment]
Not using guild commands, they are global. 

I disagree, the way the lib iterates and issues commands in `initApplicationPermissions` are triggering the rate limits. 

This, for example, solves my issue. 

```typescript
        const guidlds = this._client.guilds.cache.map((guild) => guild.id);
        for (const guild of guidlds) {
            try {
                this._client.initGuildApplicationPermissions(guild, commands)
                    .then(async res => {
                        await this._client.initGuildApplicationCommands(guild, commands);
                    }).catch(err => console.log(`guild ${guild} missing perms`));
            } catch (e) {
                console.log(`registering commands for ${guild} failed`)
            }
            await sleep(1500);
        }
    }

}
```

```typescript
function sleep(ms) {
    return new Promise((resolve) => {
        setTimeout(resolve, ms);
    });
}
```

**Comment by oceanroleplay** [comment]
> Not using guild commands, they are global.
> 
> I disagree, the way the lib iterates and issues commands in `initApplicationPermissions` and `initApplicationCommands` are triggering the rate limits.
> 
> This, for example, solves my issue.
> 
> ```ts
> const commands = this._client.applicationCommands as DApplicationCommand[];
> const guidlds = this._client.guilds.cache.map((guild) => guild.id);
>         for (const guild of guidlds) {
>             try {
>                 this._client.initGuildApplicationPermissions(guild, commands)
>                     .then(async res => {
>                         await this._client.initGuildApplicationCommands(guild, commands);
>                     }).catch(err => console.log(`guild ${guild} missing perms`));
>                 console.log(`registered commands for ${guild}`)
>             } catch (e) {
>                 console.log(`registering commands for ${guild} failed`)
>             }
>             await sleep(1500);
>         }
> ```
> 
> ```ts
> function sleep(ms) {
>     return new Promise((resolve) => {
>         setTimeout(resolve, ms);
>     });
> }
> ```

you said that you are not using but your code example is literally the opposite, you are clearly using guild commands and initiating them as well.

**Comment by oceanroleplay** [comment]
and code order is not valid as well, you are initiating permissions before initiating guild commands which will result in error for newly registered command.

**Comment by oceanroleplay** [comment]
but I do agree that race condition is not a good for lib, maybe it's better we remove it, this will likely to reduce few rate limits.

**Comment by oceanroleplay** [comment]
btw @Pho3niX90 can you share the reate  limit logs for some information's, we never really tested the lib with this much guilds. so maybe few tests may help discover the issue.

**Comment by Pho3niX90** [comment]
> and code order is not valid as well, you are initiating permissions before initiating guild commands which will result in error for newly registered command.

Keep in mind, the solution I provided above was to get around the rate limiting, so after reviewing the helper methods that registers them in the same fashion, I decided to do the same, but just with a forced sleep, between guild setup.  

Unless there is another method that doesn't iterate all guilds, checks their commands, issues a delete, issues a update, and then issues a create, then I could in theory be using that. 

Unfortunately, there were no rate limiting being printed out, I haven't investigated if there is a difference logging level for this. I first realized it once the bot stopped doing anything, went to discord, and was shown the generic msg that I am being rate limited for an hour. 

There is a 50 /s rate limit, and then a 10K p/10min rate limit. In this case, the first one was triggered multiple times since the iteration  in `initApplicationCommands` creates promises, and runs everything async.

**Comment by oceanroleplay** [comment]
> > and code order is not valid as well, you are initiating permissions before initiating guild commands which will result in error for newly registered command.
> 
> Keep in mind, the solution I provided above was to get around the rate limiting, so after reviewing the helper methods that registers them in the same fashion, I decided to do the same, but just with a forced sleep, between guild setup.
> 
> Unless there is another method that doesn't iterate all guilds, checks their commands, issues a delete, issues a update, and then issues a create, then I could in theory be using that.
> 
> Unfortunately, there were no rate limiting being printed out, I haven't investigated if there is a difference logging level for this. I first realized it once the bot stopped doing anything, went to discord, and was shown the generic msg that I am being rate limited for an hour.
> 
> There is a 50 /s rate limit, and then a 10K p/10min rate limit. In this case, the first one was triggered multiple times since the iteration in `initApplicationCommands` creates promises, and runs everything async.

the method iterate guilds only when there is guild commands, so please don't use guild commands use global command instead.

**Comment by Pho3niX90** [comment]
I see. I will investigate further, but this might be a problem again once I support "opt in" slashes, in that scenario, it would probably behave the same then once it needs to iterate again.

If I understand correctly, guild commands are those decorated with `@Guild`, if that is the case, I 100% do not have guild commands.

For example, take the below method straight out of the app. `initApplicationCommands` treated it as a guild command, and iterated it for every guild.
![image](https://user-images.githubusercontent.com/7858187/147346076-8e0b3f45-fe3e-4288-8f92-abd0e64cf2e4.png)

**Comment by oceanroleplay** [comment]
it's not necessary to use guild decorator always, it can be configured from client also, so you should join our discord server and get us know more informations, otherwise we can't help you on this.
