### ISSUE TITLE
[Feature]: Option to provide emoji to pagination buttons.

### ISSUE THREAD

**Issue by Senexis** [oceanroleplay/discord.ts#413]
### Feature?

Hey there!

Just writing in to propose a method to provide emoji to pagination buttons. Currently, whatever text is provided is always provided to the `setLabel` method with no way to access the `setEmoji` method on the `MessageButtons`. As I would like to use icons to these buttons for pagination navigation, I would like to request an `emoji` property be added to the `ButtonOptions` interface which would then optionally be set using the `setEmoji` method.

An alternative to this is to just expose the `MessageButtons` so that each of them can be overridden manually, though really the only missing set property is for setting emoji, there doesn't seem to currently be any way to hook into that one.

Cheers, and hope you had a great New Year's eve!

### Package

@discordx/utilities

**Comment by oceanroleplay** [comment]
Thanks for letting us know, I will do that as soon as possible.

**Comment by oceanroleplay** [comment]
added in v1.1.0
