### ISSUE TITLE
Access the `@Discord()` class *instance* from decorator callback functions 

### ISSUE THREAD

**Issue by multimeric** [oceanroleplay/discord.ts#414]
## Problem

Currently there are some callbacks that are defined in the annotator hooks, for example [`@SlashOption("foo", { autocomplete })
`](https://discord-ts.js.org/docs/decorators/commands/slashoption#params).

However, this only passes to the callback:

* The interaction (`AutoCompleteInteraction` class instance)
* The application (`DApplicationCommand` class instance)

We also have `MetadataStorage.instance`.

However, none of these keeps a handle to the instance of the class that has the `@Discord()` annotation. This means that we can't access the application state stored in the class instance, when we are doing things like generating the autocomplete list. I assume each of these classes are singletons, since we only ever need to construct 1 of each, so this should be possible.

## Example 
```typescript
import {DApplicationCommand, Slash, SlashOption} from "discordx";
import {AutocompleteInteraction} from "discord.js";

class Foo{
    state: string[]

    constructor() {
        this.state = [
            "a",
            "b"
        ]
    }

    @Slash("foo")
    foo(
        @SlashOption("opt1", {
            type: "STRING",
            autocomplete: (interaction: AutocompleteInteraction, cmd: DApplicationCommand) => {
                return this.state.map(item => ({name: item, value: item}));
            }
        })
        opt1: string,
    ){ }
}
```
Of course this doesn't actually work, because `this` isn't actually set to the `Foo` instance.

### Package

discordx

**Comment by Satont** [comment]
You are using that in wrong way.

```ts
@SlashOption("boption", {
      autocomplete: function myResolver(
        this: AppDiscord1,
        interaction: AutocompleteInteraction
      ) {
        // normal function, have this, so class reference is passed
        console.log(this.state);
        // resolver for option b
        interaction.respond([
          { name: "option c", value: "d" },
          { name: "option d", value: "c" },
        ]);
      },
      type: "STRING",
    })
    ```
    
    this is an example. Do not use arrow function, also first argument of function is actually your class (this context). So just rname `AppDiscord1` to `Foo` example and it will works

**Comment by Satont** [comment]
You can read docs (example) here https://discord-ts.js.org/docs/decorators/commands/slashoption#autocomplete-option

**Comment by multimeric** [comment]
Thanks for the quick reply. However I don't think this is right. The type for the `autocomplete` option is defined here, and none of the arguments is the parent object: 

https://github.com/oceanroleplay/discord.ts/blob/7238b63eed9dcf300939f47099cdf45cdaae0269/src/decorators/params/SlashOptionParams.ts#L54-L60.

Also when I try to debug their values, I get:

```typescript
    @Slash("foo")
    foo(
        @SlashOption("opt1", {
            type: "STRING",
            // @ts-ignore
            autocomplete: function(a, b, c) {
                console.log(a);
                console.log(b);
                console.log(c);
            }
        })
        opt1: string,
    ){ }

```
AutocompleteInteraction { ... }
DApplicationCommand { ... }
undefined
```

**Comment by oceanroleplay** [comment]
this is not a argument, I would recommend see more [at mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this), this is how JS works, so the answer to your question, you can use this and access class properties, just remember arrow function does not have this ability.

Join our discord server for more quick support and discussion. Thank you

**Comment by multimeric** [comment]
Sorry, I didn't realise you were referring to the `this` binding, I thought you were saying it was passed as an argument. When I use a non-arrow-function it works. Thanks!

**Comment by Satont** [comment]
> Thanks for the quick reply. However I don't think this is right. The type for the `autocomplete` option is defined here, and none of the arguments is the parent object:
> 
> https://github.com/oceanroleplay/discord.ts/blob/7238b63eed9dcf300939f47099cdf45cdaae0269/src/decorators/params/SlashOptionParams.ts#L54-L60
> 
> Also when I try to debug their values, I get:
> 
> ```ts
>     @Slash("foo")
>     foo(
>         @SlashOption("opt1", {
>             type: "STRING",
>             // @ts-ignore
>             autocomplete: function(a, b, c) {
>                 console.log(a);
>                 console.log(b);
>                 console.log(c);
>             }
>         })
>         opt1: string,
>     ){ }
> ```
> 
> ```
> AutocompleteInteraction { ... }
> DApplicationCommand { ... }
> undefined
> ```

You should name first arg of function as `this`, then it will be inherited.

**Comment by multimeric** [comment]
Here's a fully working example, by the way:

```typescript
import {DApplicationCommand, Slash, SlashOption, Discord} from "discordx";
import {AutocompleteInteraction} from "discord.js";

@Discord()
class Foo {
    state: string[]

    constructor() {
        this.state = [
            "a",
            "b"
        ]
    }

    @Slash("foo")
    foo(
        @SlashOption("opt1", {
            type: "STRING",
            autocomplete: async function(this: Foo, interaction: AutocompleteInteraction, cmd: DApplicationCommand) {
                await interaction.respond(this.state.map(item => ({name: item, value: item})));
            }
        })
        opt1: string,
    ){ }
}
```
