### ISSUE TITLE
[Bug]: Type Error SlashOptionBase, `required` set to `false`

### ISSUE THREAD

**Issue by ReevMich** [oceanroleplay/discord.ts#513]
### What happened?

A bug happened! Type error, build fails when using required options on slashOoptonsBase

### Reproduction

upgrade to project to latest discordX package. 

go to any slash command and add required option and notice error pops up

### Package

discordx

### Version

Stable

### Relevant log output

```shell
(property) required: true

Type 'true' is not assignable to type 'false'.ts(2322)
slash.d.ts(11, 5): The expected type comes from property 'required' which is declared here on type 'SlashOptionParams'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oceanroleplay** [comment]
Please see #510

**Comment by oceanroleplay** [comment]
It's now reverted back to boolean! 👍
