### ISSUE TITLE
[Feature]: Ability to collect remaining text as a single arg

### ISSUE THREAD

**Issue by lolPants** [oceanroleplay/discord.ts#576]
### Feature?

Using current `SimpleCommandOptions` logic it doesn't seem possible to collect all remaining text as a single arg.

__Example Use Case__
Asking for a user and then a message (ie: target and ban reason)
```ts
@SimpleCommand("ban")
async fn runBan(
  @SimpleCommandOption('target', { type: SimpleCommandOptionType.User })
  target: GuildMember | User | Error | undefined,
  @SimpleCommandOption('reason', { type: SimpleCommandOptionType.String })
  reason: string, // <-- want to collect all remaining text into a single string
  ctx: SimpleCommandMessage
) {
  // ...
}
```

This seems possible by abusing a custom arg splitter but this doesn't seem like an elegant way of going about it. An extra option on the `SimpleCommandOption` decorator to collect remaining args would be my preferred solution.

### Package

discordx

**Comment by oceanroleplay** [comment]
there is no simple way to determine multiple argument, hence, I would recommend to use plain argument and parse it manually,

btw only possible way to use something like

```
!ban user "this is a reason"
```

also join our discord server, where we can discuss this in depth.
