### ISSUE TITLE
[Feature]: Restrict the page change to one or more Ids

### ISSUE THREAD

**Issue by bycop** [oceanroleplay/discord.ts#636]
### Feature?

Hello,

this feature would allow to restrict the access to the page change to the ids present in an option when creating the pagination. 
In my case, I make a statistics bot and I would like all users to see the embeds but only the author can change the page.
It would avoid the trolls who have fun clicking everywhere when a user does something to disturb the use.

If you need more details doesn't hesitate to ask me
Thanks !

### Package

@discordx/pagination

**Comment by oceanroleplay** [comment]
# closed in https://github.com/oceanroleplay/discord.ts/commit/24c39c24f92f7f253b40bf56003ee41898a4ed42

exposed collector, you can now use `filter` in options.
