### ISSUE TITLE
[Bug]: Wrong import for discord_api_types in "build/*/decorators/classes/DApplicationCommand.d.ts"

### ISSUE THREAD

**Issue by PoulpY2K** [oceanroleplay/discord.ts#648]
### What happened?

After setting up the project using "create-discordx", I added the `@discordx/music` package and I tried to build a docker image via the Dockerfile, and I encountered the following error. Afterwards, I tried to run `npm run build` and I got the same error.

```TYPESCRIPT
> leu-bot@0.0.1-SNAPSHOT build
> tsc

node_modules/discordx/build/cjs/decorators/classes/DApplicationCommand.d.ts:2:104 - error TS2307: Cannot find module 'discord-api-types' or its corresponding type declarations.

2 import type { APIInteractionDataResolvedChannel, APIInteractionDataResolvedGuildMember, APIRole } from "discord-api-types";

node_modules/discordx/build/esm/decorators/classes/DApplicationCommand.d.ts:2:104 - error TS2307: Cannot find module 'discord-api-types' or its corresponding type declarations.

2 import type { APIInteractionDataResolvedChannel, APIInteractionDataResolvedGuildMember, APIRole } from "discord-api-types";
```

I checked the "discord-api-types" repo and it says we can **only** import the module by specifying the API version.

![image](https://user-images.githubusercontent.com/35991042/164780225-21284b36-4fc8-4fbd-a9cc-301901ffb8fa.png)

### 1 - Install discordx via the [create-discordx](https://github.com/oceanroleplay/discord.ts/tree/main/packages/create-discordx#-introduction) package.
- Choose npm as the package manager
- Pick the starter template

### Package

@discordx/music

### Version

Stable

### Relevant log output

```Shell
> leu-bot@0.0.1-SNAPSHOT build
> tsc

node_modules/discordx/build/cjs/decorators/classes/DApplicationCommand.d.ts:2:104 - error TS2307: Cannot find module 'discord-api-types' or its corresponding type declarations.

2 import type { APIInteractionDataResolvedChannel, APIInteractionDataResolvedGuildMember, APIRole } from "discord-api-types";

node_modules/discordx/build/esm/decorators/classes/DApplicationCommand.d.ts:2:104 - error TS2307: Cannot find module 'discord-api-types' or its corresponding type declarations.

2 import type { APIInteractionDataResolvedChannel, APIInteractionDataResolvedGuildMember, APIRole } from "discord-api-types";
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PoulpY2K** [comment]
I'm currently creating a PR to fix this issue, tell me if it is not needed.

**Comment by oceanroleplay** [comment]
can't reproduce the issue.

**Comment by PoulpY2K** [comment]
> can't reproduce the issue.

Weird, I tried multiple times on fresh projects and I always got the error. I'll check if it's not a problem on my side, but I noticed that when I add `@discordx/music` to the project, it changes the content of `node_modules/discord-api-types`.

Is it still useful that I complete the PR in your opinion?

**Comment by VictoriqueMoe** [comment]
> can't reproduce the issue.

I have seen this issue too. it's 100% an issue as the official documentation states "You can only import this module by specifying the API version you want to target"

**Comment by oceanroleplay** [comment]
> > can't reproduce the issue.
> 
> I have seen this issue too. it's 100% an issue as the official documentation states "You can only import this module by specifying the API version you want to target"

could you reproduce?

**Comment by VictoriqueMoe** [comment]
> > > can't reproduce the issue.
> > 
> > 
> > I have seen this issue too. it's 100% an issue as the official documentation states "You can only import this module by specifying the API version you want to target"
> 
> could you reproduce?

yes. and like i said, it's wrong. the PR solves this

**Comment by VictoriqueMoe** [comment]
![image](https://user-images.githubusercontent.com/27996712/164863124-b2c55fca-8d94-46fd-98a2-42fd0c57c931.png)

**Comment by oceanroleplay** [comment]
> ![image](https://user-images.githubusercontent.com/27996712/164863124-b2c55fca-8d94-46fd-98a2-42fd0c57c931.png)

that's the issue with latest version of `discord-api-types`

**Comment by oceanroleplay** [comment]
> yes. it is. that being said, we should still author it. update it internally and target `v9` on the main branch and `v10` on the dev one

alrighty

**Comment by VictoriqueMoe** [comment]
I fucking hate this api-types crap.
If we can just remove it totally that would be nice. do we even need it?

**Comment by oceanroleplay** [comment]
> I fucking hate this api-types crap. If we can just remove it totally that would be nice. do we even need it?

only if discord.js do ``export * from "discord-api-types"``, so that we don't have to manage the same version they usage, it's useless they use it as hard code and don't se peer dep.

**Comment by VictoriqueMoe** [comment]
from what i see, we just use it here:
```ts
  parseParams(
    interaction: CommandInteraction
  ): (
    | string
    | number
    | boolean
    | Role
    | APIRole
    | GuildMember
    | APIInteractionDataResolvedChannel
    | GuildBasedChannel
    | APIInteractionDataResolvedGuildMember
    | User
    | undefined
  )[] {
  ```
can we not just remove the api types?

**Comment by oceanroleplay** [comment]
> from what i see, we just use it here:
> 
> ```ts
>   parseParams(
>     interaction: CommandInteraction
>   ): (
>     | string
>     | number
>     | boolean
>     | Role
>     | APIRole
>     | GuildMember
>     | APIInteractionDataResolvedChannel
>     | GuildBasedChannel
>     | APIInteractionDataResolvedGuildMember
>     | User
>     | undefined
>   )[] {
> ```
> 
> can we not just remove the api types?

I don't recall it completely, but it has error when strict type check used.

**Comment by VictoriqueMoe** [comment]
okay, fair enough

**Comment by oceanroleplay** [comment]
released patch of `discordx`
