### ISSUE TITLE
[Feature]: Add missing nameLocalizations and descriptionLocalizations to @SlashGroup

### ISSUE THREAD

**Issue by Senexis** [oceanroleplay/discord.ts#727]
### Feature?

Title says it all. Currently it's not possible to customize the name localizations and description localizations of `@SlashGroup` while it should be possible to do so. [The Discord documentation](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure) doesn't mention anything about possible limitations on `SUB_COMMAND_GROUP`.

#### Some notes
Currently, the overloads for `@SlashGroup` don't really line up with the rest of the `Slash` related decorators. It would be great if we could have:

```js
// Currently missing overloads:
@SlashGroup(name: string, { desc, root? })
@SlashGroup(name: string, root: string, { desc })

// With proposed localization options:
@SlashGroup(name: string, { nameLocs, desc, descLocs, root? })
@SlashGroup(name: string, root: string, { nameLocs, desc, descLocs })
```

In my usecase this would allow for usage like `@SlashGroup('name', Translations.getFor('name'))` to clean up the objects. The second overload would be like `@SlashGroup('name', 'root', Translations.getFor('name'))`.

### Package

discordx

**Comment by oceanroleplay** [comment]
added in https://github.com/oceanroleplay/discord.ts/commit/7b37be0b6e44159feadf52e5bb446689e44d368f 

close issue, after tested. I have not tested it!

**Comment by Senexis** [comment]
Cool! I'll test it tonight!

(Thanks for the mention, I never got a notification!)

**Comment by oceanroleplay** [comment]
okay, well, it's added into discordx. so it will work. reopen or create new issue if it does not.
