### ISSUE TITLE
[Feature]: Add a @Alias decorator

### ISSUE THREAD

**Issue by B0tis** [oceanroleplay/discord.ts#731]
### Feature?

with this decorator it should be easier to add aliases for a command e.g: (help, h, he...).
those aliases should be than added as a normal slash command. maybe have a look at [Golden](https://github.com/arcinsolutions/Golden/blob/aca1c6e91fd2bd7af50fbca3edbbabd159fb0e87/src/modules/handlerModule/handlerModule.js), there we implemented this already but without decorators.

### Package

@discordx/utilities

**Comment by drph4nt0m** [comment]
In my option, alias dont make sense for slash commands. They might be useful for normal message content based commands, but for slash commands, you can easily know the command just by typing few letters.

**Comment by oceanroleplay** [comment]
this is tricky for utilities, I would recommend create two slash commands and create single handler. suggested usage is not widely used.

**Comment by B0tis** [comment]
okay, i will think about that.
I will close this Issue for now :smile:
