### ISSUE TITLE
[Feature]: please add the possibility of having rate limit warnings as ephemeral

### ISSUE THREAD

**Issue by B0tis** [oceanroleplay/discord.ts#732]
### Feature?

please add the possibility to react with an Ephemeral Message for Rate Limits

### Package

@discordx/utilities

**Comment by drph4nt0m** [comment]
1. You can send ephemeral messages as simple message without embeds.
2. Embeds are tricky case, you can't guarantee that the bot has embed permission in that channel. Plain text messages are the best. Even I wanted the ability to send embeds for rate limits warnings but i can't trust the user server permissions.

**Comment by drph4nt0m** [comment]
But I agree about the possibility of having rate limit warning as ephemeral.

**Comment by BotisDerG** [comment]
@drph4nt0m lol, forgot about that xD. For me it would be also enough to send limit warnings as ephemeral.
I will adjust the title and description accordingly.

**Comment by oceanroleplay** [comment]
@VictoriqueMoe

**Comment by VictoriqueMoe** [comment]
I'll do this when I can, currently I'm very unwell, but as soon as I'm better. I'll add it
