### ISSUE TITLE
[Feature]: Ability to customize when start/end buttons are displayed

### ISSUE THREAD

**Issue by Senexis** [oceanroleplay/discord.ts#758]
### Feature?

Currently the start/end buttons are only displayed if the paginator contains 10 or more items. However, since I'm using it to display articles one at a time in chronological order, I would like that to be much sooner, as soon as 3 items. Please add the ability to customize the threshold.

### Package

@discordx/pagination

**Comment by oceanroleplay** [comment]
patch released 🎉
