### ISSUE TITLE
[Bug]: SimpleCommandOption not parsing boolean well

### ISSUE THREAD

**Issue by barthofu** [oceanroleplay/discord.ts#761]
### What happened?

When using the @SimpleCommandOption with a `boolean` type, the resulted parameter is not well parsed as it will always be **true**, no matter what we type.

Example:

Command on discord             |  Output
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/66025667/173029440-1052c581-e984-4e66-a103-27814aa3dc43.png)   |  ![image](https://user-images.githubusercontent.com/66025667/173029559-657a5137-5bba-4710-a15a-fa50cd25d30e.png)

### Reproduction

```ts
@SimpleCommand("maintenance")
async maintenance(
	@SimpleCommandOption("state") state: boolean	
): Promise<void> {
		
	console.log(state)
}
```

### Package

discordx

### Version

Stable

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oceanroleplay** [comment]
patch released 🎉
