### ISSUE TITLE
[Feature]: Ability to pass custom embed color to `command.sendUsageSyntax`

### ISSUE THREAD

**Issue by ookamiiixd** [oceanroleplay/discord.ts#795]
### Feature?

Currently the `command.sendUsageSyntax` will generate random color for the embed color internally . It'd be great if we could also pass our own preferred color. This is useful because i want to make all embed messages has consistent color.

I could write custom functionality to achieve the same thing, but i think the `command.sendUsageSyntax` is already good enough.

So, i hope you consider this, thank you.

### Package

discordx

**Comment by oceanroleplay** [comment]
this function is just a example, I would recommend you to make your own method for respond.

**Comment by ookamiiixd** [comment]
i see, thanks for your respond.
