### ISSUE TITLE
[Bug]: TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by G33RY** [oceanroleplay/discord.ts#840]
### What happened?

I have installed the basic starter kit and I am getting an error:
The only thing I installed after is the `dotenv` package. 

When I remove all methods with the @Slash decorator the bot starts without problem. 

### Reproduction

https://github.com/G33RY/starter-app

### Package

discordx

### Version

Stable

### Relevant log output

```Shell
bot >> connecting discord...

Malloybot >> commands >> global
        >> adding   0 [] 
        >> updating 0 [] 
        >> deleting 0 [] 
        >> skipping 0 []

TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at Client.isApplicationCommandEqual (file:///Users/G33RY/Projects/Work/starter-app/node_modules/discordx/src/Client.ts:797:14)
    at file:///Users/G33RY/Projects/Work/starter-app/node_modules/discordx/src/Client.ts:619:17
    at Array.map (<anonymous>)
    at Client.initGuildApplicationCommands (file:///Users/G33RY/Projects/Work/starter-app/node_modules/discordx/src/Client.ts:602:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Client.initApplicationCommands (file:///Users/G33RY/Projects/Work/starter-app/node_modules/discordx/src/Client.ts:555:5)
    at async Client.<anonymous> (file:///Users/G33RY/Projects/Work/starter-app/src/main.ts:39:3)
[nodemon] app crashed - waiting for file changes before starting...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DarthJJ** [comment]
I want to second this issue. I have almost the same setup (with and without Dotenv) and I am getting the same error. 

Please see this discord chat log for more info:
![image](https://user-images.githubusercontent.com/9209118/181818913-c9c7c4fd-4866-460b-94a5-da9c79f91c2d.png)

**Comment by TeamWolfyta** [comment]
@G33RY Error occurs on version 16 of node, If your on that version (check using node -v) then try the next version, Node Version 17 or 18

**Comment by DarthJJ** [comment]
@TeamWolfyta I tried this,
Update to 18.7.0. Updated all dependencies, clean build. and still the same error.

**Comment by MatthieuLeboeuf** [comment]
Hello
I have the same issue with node version 18

**Comment by oceanroleplay** [comment]
please read this to understand issue in depth https://dev.to/benlesh/bigint-and-json-stringify-json-parse-2m8p

and use this solution for now, https://github.com/oceanroleplay/discord.ts/blob/main/packages/discordx/examples/permission/main.ts#L9

**Comment by DarthJJ** [comment]
Can confirm the workaround seems to be working. thanks @oceanroleplay

**Comment by G33RY** [comment]
> please read this to understand issue in depth https://dev.to/benlesh/bigint-and-json-stringify-json-parse-2m8p
> 
> and use this solution for now, https://github.com/oceanroleplay/discord.ts/blob/main/packages/discordx/examples/permission/main.ts#L9

Its working for me too. Thank  you.
