### ISSUE TITLE
[Feature]: I recommend you to transfer project from single repository to organisation

### ISSUE THREAD

**Issue by Waujito** [oceanroleplay/discord.ts#843]
### Feature?

This project is very large with lots of packages. And I think, it would be better if you transfered this in to organisation from single repo. In organisation you can split this project as packages.

### Package

discordx

**Comment by oceanroleplay** [comment]
I wish, but unable to get the org username, I wish for.

**Comment by Waujito** [comment]
`discord_ts`, `discord_x`, `discord-x`, `discordtsx` names are free

**Comment by oceanroleplay** [comment]
> 

except `discordtsx`, others are not available.

**Comment by drph4nt0m** [comment]
I would also like to suggest, `xdiscord`, `discordtx`

**Comment by oceanroleplay** [comment]
nope, that will be `discordx-xxx` because @VictoriqueMoe won't agree without it 😅

**Comment by drph4nt0m** [comment]
I actually checked discordxxx, but it is taken. :(

**Comment by oceanroleplay** [comment]
`discord-ts` could be our name, but the owner of that account has not agreed to give up the name.

**Comment by drph4nt0m** [comment]
I personally would want to avoid `-`s. They are just so irritating when typing URLs.

**Comment by TeamWolfyta** [comment]
You might be able to email GitHub requested an account like `discordx ` be removed so you can use it, I don't know if GitHub does this but some services will remove inactive / abandoned accounts to make way for new / active accounts to use the name.

**Comment by drph4nt0m** [comment]
I dont think they will do that. Because there was big attack similar to this recently because of few popular python packages who's original authors deleted their GitHub accounts and someone else "hijacked" that account and put malicious code into those packages via their account. It's complicated. Ref: https://www.theregister.com/2022/05/24/pypi_ctx_package_compromised/

**Comment by TeamWolfyta** [comment]
Hmmm didn't know, I mean `discord.ts` is very active and with a fair few people backing it whereas the user `discordx`, They might consider that.

**Comment by drph4nt0m** [comment]
Yeah. Maybe. But its very hard to convince them.

**Comment by TeamWolfyta** [comment]
I guess we'll see what @oceanroleplay want's to do.

**Comment by drph4nt0m** [comment]
@oceanroleplay wants to use `discord-xxx` 👀

**Comment by VictoriqueMoe** [comment]
I have talked about this before. and while i agree we should move to an organisation. we need to get the name right, and currently, all the ones we want are taken. 

`discord-xxx` is great, only because i am bias. 

but we can always name it something less abstract.

I am happy to pay for a paid `Team` account for it. let me know the name and i can create it and assign @oceanroleplay as the owner

**Comment by TeamWolfyta** [comment]
+1 for discord-xxx 😀

**Comment by VictoriqueMoe** [comment]
![image](https://user-images.githubusercontent.com/27996712/182872340-e90bf815-f66c-49d7-926a-1e16fe08310e.png)

**Comment by oceanroleplay** [comment]
first, `discord.ts`, then `discordx` and now, `discord-xxx`. I would say, sorry. I am not ready for the change.

**Comment by oceanroleplay** [comment]
@VictoriqueMoe maybe you should try with owner of `discord-ts`. Maybe offer him some money... or something...

**Comment by VictoriqueMoe** [comment]
> @VictoriqueMoe maybe you should try with owner of `discord-ts`. Maybe offer him some money... or something...

I shall flirt with him and offer him things.

> first, `discord.ts`, then `discordx` and now, `discord-xxx`. I would say, sorry. I am not ready for the change.

We have to change, sorry, Harry, but i agree, we need to do it.

**Comment by kaname-png** [comment]
Better merge both names.
```
discordx + discord-ts = discord-tsx
```
And good news, that name is available.

**Comment by TeamWolfyta** [comment]
Not a bad name actually, Would fix the confusing problem where the repo name is called discord.ts but the package is called discordx xD

**Comment by eternalfusion** [comment]
> Better merge both names.
> 
> ```
> discordx + discord-ts = discord-tsx
> ```
> 
> And good news, that name is available.

`tsx` confuses with `.tsx` file extension which means `jsx` notation in TypeScript used by `React` for example

**Comment by drph4nt0m** [comment]
Package is already `discordx`. Let's make the repo organization as `xdiscord`.

**Comment by oceanroleplay** [comment]
@Waujito I would like yo inform you that this concern is under consideration since months, we will move to organization in near future. Thanks for reaching out us for this.
